### ISSUE TITLE
Tests on some versions of Python are failing due to tox

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/actions#5]
**Describe the bug**
Tests are failing on Python 3.8 and 3.9 seemingly due to a tox error (see [cellfinder-napari tests](https://github.com/brainglobe/cellfinder-napari/actions/runs/3311806698)). 

```
Error: ERROR:   py39: InvocationError for command /home/runner/work/cellfinder-napari/cellfinder-napari/.tox/py39/bin/python -m pip install --exists-action w .tox/.tmp/package/1/cellfinder-napari-0.0.20.zip (exited with code 1)
```

**To Reproduce**
Run tests using `brainglobe/actions/test@v1` and Python 3.9

**Additional context**
[Possibly the same issue](https://github.com/tox-dev/tox/issues/1589)

**Comment by dstansby** [comment]
Since we're archiving this repo, I'll close this. If a similar issue comes up we can tackle it in the fork.
